spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=false
    username: chatUser
    password: chatUser
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false